### ISSUE TITLE
Need for include scss

### ISSUE THREAD

**Issue by Ismaestro** [maxisam/ngx-progressive-image-loader#9]
Hello!

Nice job !!

Just a question, why do we need to include some sass styles? Should not be enough import the module? It's just that I want to use it in a cleaner way ...

Thanks and best regards

**Comment by maxisam** [comment]
Well, it allows you to do more customization.

**Comment by Ismaestro** [comment]
In that case I think we should pass the config in the forRoot method and not as a SASS import (just the scale?). I want to use your project [here](https://github.com/Ismaestro/angular7-example-app) btw.

**Comment by maxisam** [comment]
Feel free to use it. Remember to use the latest beta version ^4.0.0-beta.7. I used it on my production project and it works fine. 

for some config, I put it in forRoot method. But there are just too many things that users might want to customize it. I don't want to lose the flexibility. 
Besides, this way is not really that bad. If you want to customize angular material or change a theme, you need to do things like this as well. 

Also, I am debating if I should use service instead of component. I need more time to think through it.
